version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 7.0
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - facivon.ico
    - styles/main.css
    - images/*